homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 22
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml
  # Auth Provider
  auth_providers: 
   - type: trusted_networks 
     trusted_networks: 
      - 127.0.0.1 
      - ::1 
      - 192.168.0.0/24
   - type: homeassistant

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Frontend and HTTP
frontend:
  themes: !include themes.yaml
  javascript_version: auto

http:
  base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  
# Discover some devices automatically
discovery:
  ignore:
    - samsung_tv
  enable:
    - homekit
    
# Stream
stream:

# Lovelace Mode
lovelace:
  mode: yaml

# Recorder
recorder:
  db_url: !secret recorder

# Speedtest.net
speedtestdotnet:
  scan_interval:
    minutes: 240
  server_id: 12372
  monitored_conditions:
    - ping
    - download
    - upload

# Calendar
calendar:
  - platform: caldav
    url: !secret url_4
    username: !secret icloud_user
    password: !secret icloud_app_specific_password
    calendars:
      - 'Schings'
      - 'Jimmy'
      - 'Stephanie'
      - 'Holiday'

# Tado
tado:
  username: !secret tado_usr
  password: !secret tado_pwd

# Custom Updater
custom_updater:
  track:
    - components
    - cards
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/kuuji/button-card/master/tracker.json
    - https://raw.githubusercontent.com/nervetattoo/simple-thermostat/allow-updates/tracker.json
    - https://raw.githubusercontent.com/bramkragten/custom-ui/master/updater.json
    - https://raw.githubusercontent.com/ljmerza/calendar-card/master/custom_updater.json
    - https://raw.githubusercontent.com/kalkih/simple-weather-card/master/tracker.json
    - https://raw.githubusercontent.com/maykar/lovelace-swipe-navigation/master/tracker.json
    - https://raw.githubusercontent.com/peternijssen/lovelace-postnl/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
    - https://raw.githubusercontent.com/ljmerza/light-entity-card/master/custom_updater.json
  component_urls:
    - https://raw.githubusercontent.com/eelcohn/home-assistant-rdw/master/custom_updater.json

# Sabnzbd
sabnzbd:
  api_key: !secret sabnzbd_api_key
  host: 192.168.0.34
  name: sabnzbd
  port: 8081
  sensors:
    - current_status
    - speed
    - queue_count
    - queue_size
    - queue_remaining
    - disk_size
    - disk_free
    - total_size

# Iframe
panel_iframe:
  sonarr:
    title: "Sonarr"
    url: !secret url_2
    icon: "mdi:television"
  couchpotato:
    title: "Radarr"
    url: !secret url_3
    icon: "mdi:sofa"
  serveressentials:
    title: "Windows Cloud"
    url: !secret url_1
    icon: "mdi:windows"

# Homekit Configuration
homekit:
  auto_start: False
  filter:
    include_domains:
      - alarm_control_panel
      - climate
      - scene
    include_entities:
      - alarm_control_panel.home_alarm
      - light.eettafel_lamp
  entity_config:
    alarm_control_panel.home_alarm:
      code: !secret alarm_code

# Text to speech
tts:
  - platform: google_translate
  
# iOS and Notifications
ios:
  push:
    categories:
      - name: Afzuigkap Alert
        identifier: 'afzuigkap_alert'
        actions:
          - identifier: 'AFZUIGKAP_UITZETTEN'
            title: 'Afzuigkap Uitschakelen'
          - identifier: 'AFZUIGKAP_ANNULEREN'
            title: 'Annuleren'
            destructive: yes
      - name: Alarm Alert
        identifier: 'alarm_alert'
        actions:
          - identifier: 'ALARM_UITSCHAKELEN'
            title: 'Alarm Uitschakelen'
          - identifier: 'ALARM_ANNULEREN'
            title: 'Annuleren'
            destructive: yes
      - name: Smoke Alert
        identifier: 'smoke_alert'
        actions:
          - identifier: 'SMOKE_ALARM_INSCHAKELEN'
            title: 'Rookmelder Dempen (Tijdelijk)'
          - identifier: 'SMOKE_ANNULEREN'
            title: 'Annuleren'
            destructive: yes
      - name: Receiver Aanzetten
        identifier: 'receiver_alert'
        actions:
          - identifier: 'RECEIVER_INSCHAKELEN'
            title: 'Receiver Inschakelen'
          - identifier: 'TV_UITSCHAKELEN'
            title: 'TV Uitschakelen'
          - identifier: 'RECEIVER_ANNULEREN'
            title: 'Annuleren'
            destructive: yes
      - name: Alarm Activeren
        identifier: 'alarm_activeren'
        actions:
          - identifier: 'ALARM_AFWEZIG'
            title: 'Alarm Afwezig'
          - identifier: 'ALARM_THUIS'
            title: 'Alarm Thuis'
          - identifier: 'ALARM_ANNULEREN'
            title: 'Annuleren'
            destructive: yes
      - name: Droger Alert
        identifier: 'droger_alert'
        actions:
          - identifier: 'DROGER_UITSCHAKELEN'
            title: 'Droger Uitschakelen'
          - identifier: 'VAATWASSER_INSCHAKELEN'
            title: 'Vaatwasser Inschakelen'
          - identifier: 'DROGER_ANNULEREN'
            title: 'Annuleren'
            destructive: yes
      - name: Wasmachine Alert
        identifier: 'wasmachine_alert'
        actions:
          - identifier: 'WASMACHINE_UITSCHAKELEN'
            title: 'Wasmachine Uitschakelen'
          - identifier: 'VAATWASSER_INSCHAKELEN'
            title: 'Vaatwasser Inschakelen'
          - identifier: 'WASMACHINE_ANNULEREN'
            title: 'Annuleren'
            destructive: yes
      - name: Vaatwasser Alert
        identifier: 'vaatwasser_alert'
        actions:
          - identifier: 'VAATWASSER_UITSCHAKELEN'
            title: 'Vaatwasser Uitschakelen'
          - identifier: 'VAATWASSER_ANNULEREN'
            title: 'Annuleren'
            destructive: yes
      - name: Bijkeuken Alert
        identifier: 'bijkeuken_alert'
        actions:
          - identifier: 'SLA_ALARM'
            title: 'SLA ALARM'
            destructive: yes
          - identifier: 'AFWEZIG_ALARM'
            title: 'Alarm Afwezig'
            destructive: yes
          - identifier: 'THUIS_ALARM'
            title: 'Alarm Thuis'
          - identifier: 'BIJKEUKEN_ANNULEREN'
            title: 'Annuleren'
            destructive: yes
      - name: Toilet Alert
        identifier: 'toilet_alert'
        actions:
          - identifier: 'SLA_ALARM'
            title: 'SLA ALARM'
            destructive: yes
          - identifier: 'AFWEZIG_ALARM'
            title: 'Alarm Afwezig'
            destructive: yes
          - identifier: 'THUIS_ALARM'
            title: 'Alarm Thuis'
          - identifier: 'TOILET_ANNULEREN'
            title: 'Annuleren'
            destructive: yes
      - name: Meds Alert
        identifier: 'meds_alert'
        actions:
          - identifier: 'MEDS_ALARM'
            title: 'Voltooid'
          - identifier: 'MEDS_ANNULEREN'
            title: 'Herhaal over 20min'
            destructive: yes
      - name: Camera
        identifier: 'camera'
        actions:
          - identifier: 'SLA_ALARM'
            title: 'SLA ALARM'
            destructive: yes
            authenticationRequired: true
          - identifier: 'AFWEZIG_ALARM'
            title: 'Alarm Inschakelen'
          - identifier: 'TOILET_ANNULEREN'
            title: 'Annuleren'
            destructive: yes

# Weather
weather:
  - platform: darksky
    api_key: !secret darksky
    mode: daily
    
# Notify
notify:
  - name: ios_notifier
    platform: group
    services:
      - service: mobile_app_iphone_jimmy
      - service: mobile_app_iphone_stephanie
      
# Xiaomi Aqara/Mija
xiaomi_aqara:
  gateways:
    - key: !secret xiaomi_gateway
  discovery_retry: 10

# All Sensors/Switches ETC.
sensor: !include sensor.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
camera: !include camera.yaml
media_player: !include media_player.yaml
light: !include light.yaml
switch: !include switch.yaml
input_boolean: !include input_boolean.yaml
zone: !include zone.yaml
device_tracker: !include device_tracker.yaml
alarm_control_panel: !include alarms.yaml
scene: !include scenes.yaml
shell_command: !include shell_command.yaml
input_select: !include input_select.yaml
python_script: