# Home Assistant Config 
homeassistant:
  # Customization file
  customize: !include_dir_merge_named configuration/customize/ # Changed/Added in 0.13.2
  # Auth Provider
  auth_providers: 
   - type: trusted_networks 
     trusted_networks: 
      - 127.0.0.1 
      - ::1 
      - 192.168.0.0/24
   - type: homeassistant

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:



# HACS
hacs:
  token: !secret HACS

# Frontend Themes
frontend:
  themes: !include_dir_named configuration/themes/
  javascript_version: auto

# SSL
http:
  base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  
# Discover some devices automatically
discovery:
  ignore:
    - samsung_tv
    
# Stream
stream:

# Lovelace Mode
lovelace:
  mode: yaml

# Recorder
recorder:
  db_url: !secret recorder
  purge_keep_days: 3
  exclude:
    domains:
      - automation
    entities:
      - sensor.xiaomi_map
  
# Speedtest.net
speedtestdotnet:
  scan_interval:
    minutes: 240
  server_id: 12372
  monitored_conditions:
    - ping
    - download
    - upload

# Calendar
calendar:
  - platform: caldav
    url: !secret url_4
    username: !secret icloud_user
    password: !secret icloud_app_specific_password

# Tado
tado:
  username: !secret tado_usr
  password: !secret tado_pwd

# Iframe
panel_iframe:
  sonarr:
    title: "Sonarr"
    url: !secret url_2
    icon: "mdi:television"
  radarr:
    title: "Radarr"
    url: !secret url_3
    icon: "mdi:sofa"
  nzbget:
    title: "NZBGet"
    url: !secret url_6
    icon: "mdi:download"
  serveressentials:
    title: "Windows Cloud"
    url: !secret url_1
    icon: "mdi:windows"

# Homekit Configuration
homekit: !include configuration/homekit/homekit.yaml # Changed/Added in 0.13.2

# Text to speech
tts:
  - platform: google_translate
  
# iOS and Notifications
ios: !include configuration/ios/ios.yaml # Changed/Added in 0.13.2

# Weather
weather:
  - platform: darksky
    api_key: !secret darksky
    mode: daily
    
# Notify
notify:
  - name: ios_notifier
    platform: group
    services:
      - service: mobile_app_iphone
      - service: mobile_app_iphone_stephanie
      
# Xiaomi Aqara/Mija
xiaomi_aqara:
  gateways:
    - key: !secret xiaomi_gateway
  discovery_retry: 10

# All Sensors/Switches ETC.
sensor: !include_dir_merge_list configuration/sensor/
group: !include_dir_merge_named configuration/groups/ # Changed/Added in 0.13.2
automation: !include_dir_merge_list configuration/automations/
script: !include_dir_merge_named configuration/scripts/
camera: !include configuration/camera/camera.yaml # Changed/Added in 0.13.2
media_player: !include configuration/media_player/media_player.yaml # Changed/Added in 0.13.2
light: !include configuration/light/light.yaml # Changed/Added in 0.13.2
switch: !include_dir_merge_list configuration/switch/
input_boolean: !include_dir_merge_named configuration/input_boolean/ # Changed/Added in 0.13.2
zone: !include configuration/zone/zone.yaml # Changed/Added in 0.13.2
device_tracker: !include configuration/device_tracker/device_tracker.yaml # Changed/Added in 0.13.2
alarm_control_panel: !include configuration/alarm_control_panel/alarms.yaml # Changed/Added in 0.13.2
scene: !include_dir_merge_list configuration/scenes/
shell_command: !include configuration/shell_command/shell_command.yaml # Changed/Added in 0.13.2
input_select: !include_dir_merge_named configuration/input_select/ # Changed/Added in 0.13.2

# Python Script (Birthday Sensor)
python_script:

# Vacuum (Roborock S55)
vacuum:
  - platform: xiaomi_miio
    host: 192.168.0.11
    token: !secret roborock

# Browser-Mod
browser_mod:
  devices:
    24cb89cc-be714b7d:
      name: Jimmy

# Grocy # Changed/Added in 0.13.0
grocy:
  url: !secret grocy_url
  api_key: !secret grocy_api
  sensor:
    - enabled: true

# Apple TV (MRP) # Changed/Added in 0.13.0
apple_tv_mrp:
  - name: Woonkamer Apple TV
    host: 192.168.0.95
    port: 49153
#    credentials: !secret atv_pwd
  - name: Slaapkamer Apple TV
    host: 192.168.0.96
    port: 49152

# Plex # Changed/Added in 0.13.0
plex:
  host: 192.168.0.31
  token: !secret plex
  media_player:
    use_episode_art: false

# NZBget
nzbget:
  host: !secret url_5
  port: 9090
  ssl: true
  username: !secret nzbget_usr
  password: !secret nzbget_pwd