
# EXAMPLE CONFIGURATION.YAML, IT CONTAINS ALL THE NECESSARY LINES YOU NEED IN YOUR OWN CONFIGURATION.YAML
# DO NOT USE THIS FILE!!!!!

homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages/

lovelace:
  mode: storage
