# Home Assistant Config 
homeassistant:
  # Customization file
  customize: !include configuration/customize.yaml
  # Auth Provider
  auth_providers: 
   - type: trusted_networks 
     trusted_networks: 
      - 127.0.0.1 
      - ::1 
      - 192.168.0.0/24
   - type: homeassistant

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# HACS
hacs:
  token: !secret HACS

# Frontend & SSL
frontend:
  themes: !include_dir_named configuration/themes # Changed/Added in 0.13.0
  javascript_version: auto

http:
  base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  
# Discover some devices automatically
discovery:
  ignore:
    - samsung_tv
    
# Stream
stream:

# Lovelace Mode
lovelace:
  mode: yaml

# Recorder
recorder:
  db_url: !secret recorder
  purge_keep_days: 3
  exclude:
    domains:
      - automation
    entities:
      - sensor.xiaomi_map
  
# Speedtest.net
speedtestdotnet:
  scan_interval:
    minutes: 240
  server_id: 12372
  monitored_conditions:
    - ping
    - download
    - upload

# Calendar
calendar:
  - platform: caldav
    url: !secret url_4
    username: !secret icloud_user
    password: !secret icloud_app_specific_password

# Tado
tado:
  username: !secret tado_usr
  password: !secret tado_pwd

# Iframe
panel_iframe:
  sonarr:
    title: "Sonarr"
    url: !secret url_2
    icon: "mdi:television"
  radarr:
    title: "Radarr"
    url: !secret url_3
    icon: "mdi:sofa"
  nzbget:
    title: "NZBGet"
    url: !secret url_6
    icon: "mdi:download"
  serveressentials:
    title: "Windows Cloud"
    url: !secret url_1
    icon: "mdi:windows"

# Homekit Configuration
homekit: !include configuration/homekit.yaml

# Text to speech
tts:
  - platform: google_translate
  
# iOS and Notifications
ios: !include configuration/ios.yaml

# Weather
weather:
  - platform: darksky
    api_key: !secret darksky
    mode: daily
    
# Notify
notify:
  - name: ios_notifier
    platform: group
    services:
      - service: mobile_app_iphone
      - service: mobile_app_iphone_stephanie
      
# Xiaomi Aqara/Mija
xiaomi_aqara:
  gateways:
    - key: !secret xiaomi_gateway
  discovery_retry: 10

# All Sensors/Switches ETC.
sensor: !include configuration/sensor.yaml
group: !include configuration/groups.yaml
automation: !include configuration/automations.yaml
script: !include configuration/scripts.yaml
camera: !include configuration/camera.yaml
media_player: !include configuration/media_player.yaml
light: !include configuration/light.yaml
switch: !include configuration/switch.yaml
input_boolean: !include configuration/input_boolean.yaml
zone: !include configuration/zone.yaml
device_tracker: !include configuration/device_tracker.yaml
alarm_control_panel: !include configuration/alarms.yaml
scene: !include configuration/scenes.yaml
shell_command: !include configuration/shell_command.yaml
input_select: !include configuration/input_select.yaml

# Python Script (Birthday Sensor)
python_script:

# Vacuum (Roborock S55)
vacuum:
  - platform: xiaomi_miio
    host: 192.168.0.11
    token: !secret roborock

# Browser-Mod
browser_mod:
  devices:
    5b4e295f-d8a2f862:
      name: Jimmy

# Grocy # Changed/Added in 0.13.0
grocy:
  url: !secret grocy_url
  api_key: !secret grocy_api
  sensor:
    - enabled: true

# Apple TV (MRP) # Changed/Added in 0.13.0
apple_tv_mrp:
  - name: Woonkamer Apple TV
    host: 192.168.0.95
    port: 49153
#    credentials: !secret atv_pwd
  - name: Slaapkamer Apple TV
    host: 192.168.0.96
    port: 49152

# Plex # Changed/Added in 0.13.0
plex:
  host: 192.168.0.31
  token: !secret plex
  media_player:
    use_episode_art: false