homeassistant:
  customize: !include customize.yaml

customizer:
  custom_ui: local

frontend:
  themes: !include_dir_named configuration/themes/
  javascript_version: auto

stream:

lovelace_gen: !include_dir_merge_named global_config/

lovelace:
  mode: yaml

recorder:
  purge_keep_days: 3
  exclude:
    domains:
      - automation

python_script:

browser_mod: