# Custom Card Resources
resources:
  !include lovelace/resources/resources.yaml
 
# Compact Custom Header
# You will need to hide views if you want to
# have views that behave like popup cards!
cch:
  menu: hide
  options: hide
  notifications: hide
  voice: hide
  header: false
  chevrons: false
  notify_indicator_color: "#e80000"
  swipe: true
  swipe_wrap: false
  background: 'rgba(0,0,0,0.3)'
  hide_tabs: '5 to 30'
  default_tab: 1
   
# Decluttering Templates
# These are the templates used to avoid too much
# duplicate code.
decluttering_templates:
  !include lovelace/decluttering_templates/decluttering_templates.yaml
       
# Views
# The following 5 views are swipable, the order
# of these 5 files is the swipe order as well.
# The first view is the page 0. In my setup
# the interface defaults to view 1.
title: Home
background: var(--background-image)
views:
  - !include lovelace/views/climate.yaml
  - !include lovelace/views/main_view.yaml
  - !include lovelace/views/lights.yaml
  - !include lovelace/views/devices.yaml
  - !include lovelace/views/security.yaml
# The views below are used as fake popup cards
# They are non swipable and will behave just like
# a popup card or conditional cards. The order of
# these files will not change anything.
  - !include lovelace/views/vacuum.yaml
  - !include lovelace/views/vacuum-zoned-cleaning.yaml
  - !include lovelace/views/alarm.yaml
  - !include lovelace/views/jimmy.yaml
  - !include lovelace/views/stephanie.yaml
  - !include lovelace/views/tala.yaml
  - !include lovelace/views/scenes.yaml
  - !include lovelace/views/main_menu.yaml
  - !include lovelace/views/cleaning.yaml
  - !include lovelace/views/floorplan.yaml
  - !include lovelace/views/remote.yaml
  - !include lovelace/views/links.yaml
  - !include lovelace/views/calendar.yaml
  - !include lovelace/views/laundry.yaml
  - !include lovelace/views/media.yaml
  - !include lovelace/views/downloads.yaml
  - !include lovelace/views/energy.yaml
  - !include lovelace/views/other.yaml
  - !include lovelace/views/currently_on.yaml
  - !include lovelace/views/location.yaml
  - !include lovelace/views/themes.yaml
  - !include lovelace/views/postnl-jimmy.yaml
  - !include lovelace/views/postnl-stephanie.yaml
  - !include lovelace/views/weather.yaml

# Note that this order and the way this works might change in the near future.
# It will be the removal of swipe-cards in favor of CCH swipe gestures.