# Custom Card Resources
resources:
  !include lovelace/resources/resources.yaml
 
# Compact Custom Header
cch:
  menu: hide
  options: hide
  notifications: hide
  voice: hide
  header: true
  chevrons: false
  notify_indicator_color: "#e80000"
  swipe: true
  swipe_wrap: false
  background: 'rgba(0,0,0,0.3)'
  default_tab: 2
   
# Decluttering Templates
decluttering_templates:
  !include lovelace/decluttering_templates/decluttering_templates.yaml
       
# Views
title: Home
background: var(--background-image)
views:
  - !include lovelace/views/security.yaml
  - !include lovelace/views/climate.yaml
  - !include lovelace/views/main_view.yaml
  - title: Lights
    path:  lights
    popup_cards:
      !include lovelace/popup-cards/light-popup.yaml
    cards:
      !include lovelace/views/lights.yaml
  - title: Devices
    path: devices
    cards:
      !include lovelace/views/devices.yaml