- title: Automations
  path:  automations
  cards:
    - type: vertical-stack
      cards:
        - type: custom:decluttering-card
          template: quick-access-menu 
          variables:
            - name1: Lights
            - icon1: mdi:floor-lamp # Changed/Added in 0.13.0
            - path1: lights
        - type: custom:decluttering-card
          template: header 
          variables:
            - content: '## Automations'
        - type: custom:decluttering-card
          template: header 
          variables:
            - content: '##### Turn Automations on/off'
        - type: horizontal-stack
          cards:
            - !include ../includes/blank-card.yaml
            - type: custom:decluttering-card
              template: button 
              variables:
                - entity: group.film_kijken_automation
                - name: Dim Light
                - icon: mdi:movie # Changed/Added in 0.13.0
                - label: Movie
                - show_state: true
                - grid:
                    - grid-template-areas: '"i" "n" "l" "s"' 
                    - grid-template-columns: 1fr 
                    - grid-template-rows: 1fr min-content min-content               
                - tap_action:
                    action: toggle
                    haptic: light
            - type: custom:decluttering-card
              template: button 
              variables:
                - entity: group.deur_notifications
                - name: Door
                - icon: mdi:door # Changed/Added in 0.13.0
                - label: Notifications
                - show_state: true
                - grid:
                    - grid-template-areas: '"i" "n" "l" "s"' 
                    - grid-template-columns: 1fr 
                    - grid-template-rows: 1fr min-content min-content              
                - tap_action:
                    action: toggle
                    haptic: light
            - type: custom:decluttering-card
              template: button 
              variables:
                - entity: group.vaatwasser_starten
                - name: Dishwasher On
                - icon: mdi:dishwasher # Changed/Added in 0.13.0
                - label: After Laundry
                - show_state: true
                - grid:
                    - grid-template-areas: '"i" "n" "l" "s"' 
                    - grid-template-columns: 1fr 
                    - grid-template-rows: 1fr min-content min-content              
                - tap_action:
                    action: toggle
                    haptic: light
            - !include ../includes/blank-card.yaml
        - type: horizontal-stack
          cards:
            - !include ../includes/blank-card.yaml
            - type: custom:decluttering-card
              template: button 
              variables:
                - entity: automation.motion_detected_no_one_home_gallerij
                - name: Movement
                - label: Notification
                - icon: mdi:walk # Changed/Added in 0.13.0
                - show_state: true
                - grid:
                    - grid-template-areas: '"i" "n" "l" "s"' 
                    - grid-template-columns: 1fr 
                    - grid-template-rows: 1fr min-content min-content              
                - tap_action:
                    action: toggle
                    haptic: light
            - type: custom:decluttering-card
              template: button 
              variables:
                - entity: group.all_automations
                - name: Automations
                - icon: mdi:alpha-a-box
                - label: All # Changed/Added in 0.13.0
                - show_state: true
                - grid:
                    - grid-template-areas: '"i" "n" "l" "s"' 
                    - grid-template-columns: 1fr 
                    - grid-template-rows: 1fr min-content min-content              
                - tap_action:
                    action: toggle
                    haptic: light
            - type: custom:button-card
              color_type: blank-card
              aspect_ratio: 1/1
            - !include ../includes/blank-card.yaml
        - !include ../includes/bottom-card.yaml  