view_config: # For examples check out https://github.com/jimz011/homekit-infused/tree/4.x.x-personal

# Home
  home:
    title: greeting
    show_in_navbar: true
    show_in_menu: false
    columns: 
      buttons: 4
    favorites:
      hide_title: true
    welcome_message: true

  menu:
    show_in_navbar: true
    show_in_menu: false
    icon: mdi:apps
    subtitle: "[[[ return `Homekit Infused Version: ${states['sensor.hki_current_version'].state}`; ]]]"
    search_card:
    favorites: 
    menu: 
    hki_menu:

# You can remove this line and the example views below or continue to build on them.

# Example
  lights:
    icon: mdi:floor-lamp
    subtitle: Overview
    devices:
      my_lights:
        - light.my_lamp
 














