view_config: # For examples check out https://github.com/jimz011/homekit-infused/tree/4.x.x-personal

# Home
  home:
    title: greeting
    show_in_navbar: true
    show_in_menu: false
    columns: 
      buttons: 4
    favorites:
      show_title: false
    welcome_message: true

  menu:
    show_in_navbar: true
    show_in_menu: false
    icon: mdi:apps
    subtitle: "[[[ return `Homekit Infused Version: ${states['sensor.hki_current_version'].state}`; ]]]"
    search:
    favorites: 
    menu: 
    hki_menu:

# You can remove this line and the example views below or continue to build on them.
# NOTE: If you have no views it might throw an error, you can safely ignore this since the error will go away once you setup some views!

# Example
  lights:
    icon: mdi:floor-lamp
    show_in_favorites: true
    subtitle: Overview
    devices:
      - title: My Example
        entities:
          - sensor.time_date
 














