### IKEA Tradfri dimmers for use with deCONZ
### The icons in the description are the icons
### shown on the actual remote for convenience

## Bedroom

# Button Middle (power icon)
- alias: 'Bedroom IKEA button middle tap_action'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ab_slaapkamer
      event: 1002
  action:
    - service: light.toggle
      entity_id: light.slaapkamer
    - service: light.turn_off
      entity_id:
        - light.slaapkamer_kast
        - light.slaapkamer_bed

# Button Left (left-arrow icon)
- alias: 'Bedroom IKEA button left tap_action'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ab_slaapkamer
      event: 4002
  action:
    service: light.toggle
    entity_id: light.nachtkastje_stephanie

# Button Right (right-arrow icon)
- alias: 'Bedroom IKEA button right tap_action'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ab_slaapkamer
      event: 5002
  action:
    service: light.toggle
    entity_id: light.nachtkastje_jimmy

# Button Top (brightness-up icon)
- alias: 'Bedroom IKEA button top tap_action'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ab_slaapkamer
      event: 2001
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.slaapkamer
        brightness: >
          {% set bri = state_attr('light.slaapkamer', 'brightness') | int %}
          {{ [bri+30, 249] | min }}

# Button Down (brightness-down icon)
- alias: 'Bedroom IKEA button down tap_action'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ab_slaapkamer
      event: 3001
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.slaapkamer
        brightness: >
          {% set bri = state_attr('light.slaapkamer', 'brightness') | int %}
          {{ [bri-30, 0] | max }}

