- title: HKI Settings
  path: hki_settings_calendar
  cards:    
    - type: vertical-stack
      cards:
        - !include
          - '../../templates/system_header_advanced.yaml'
          - name: Calendar
            icon: mdi:calendar
            content: "HKI {{ states.input_text.name_header_settings.state }}"
            system_header: input_boolean.config_header
        - type: conditional
          conditions:
            - entity: input_boolean.edit_mode
              state: "on"
          card:
            !include
            - '../../templates/edit_mode_warning.yaml'
            - template: nothing_to_edit.yaml
        - !include
          - '../../templates/settings_back_button.yaml'
          - background_color: LightSeaGreen
        - type: custom:layout-card
          cards:
            - type: vertical-stack
              cards:
                - type: custom:layout-card
                  cards:
                    - type: conditional
                      conditions:
                        - entity: input_boolean.system_help
                          state: "on"
                      card:
                        type: markdown
                        style: |
                          ha-card {
                            background: rgba(0, 0, 0, 0.5);
                            border-radius: {{ states('input_select.border_radius') }};
                            box-shadow: {{ states('input_select.box_shadow') }};
                            font-size: 13px;
                            font-family: Helvetica;
                            color: white;
                          }                    
                        content: >
                          **Calendar:** Calendar setup, for now it only applies to the frontpage widget and it only accepts one master calendar, this will be expanded in the future.
                    - type: entities
                      title: House Calendar
                      style: |
                        ha-card {
                          border-radius: {{ states('input_select.border_radius') }};
                          box-shadow: {{ states('input_select.box_shadow') }};
                          overflow: hidden;
                        }                        
                      show_header_toggle: false
                      entities:
                        - entity: input_text.house_calendar_entity
                          type: 'custom:text-input-row'