- title: HKI Settings
  path: hki_settings_weather
  cards:    
    - type: vertical-stack
      cards:
        - !include
          - '../../templates/system_header_advanced.yaml'
          - name: Weather
            icon: mdi:weather-partly-cloudy
            content: "HKI {{ states.input_text.name_header_settings.state }}"
            system_header: input_boolean.config_header
        - type: conditional
          conditions:
            - entity: input_boolean.edit_mode
              state: "on"
          card:
            !include
            - '../../templates/edit_mode_warning.yaml'
            - template: nothing_to_edit.yaml
        - !include
          - '../../templates/settings_back_button.yaml'
          - background_color: LightSeaGreen
        - type: custom:layout-card
          cards:
            - type: vertical-stack
              cards:
                - type: custom:layout-card
                  cards:
                    - type: conditional
                      conditions:
                        - entity: input_boolean.system_help
                          state: "on"
                      card:
                        type: markdown
                        style: |
                          ha-card {
                            background: rgba(0, 0, 0, 0.5);
                            border-radius: {{ states('input_select.border_radius') }};
                            box-shadow: {{ states('input_select.box_shadow') }};
                            font-size: 13px;
                            font-family: Helvetica;
                            color: white;
                          }                    
                        content: >
                          **Weather:** Settings for weather are for both the frontpage and weather view. Set up your entities here.
                    - type: entities
                      title: Weather
                      show_header_toggle: false                          
                      style: |
                        ha-card {
                          border-radius: {{ states('input_select.border_radius') }};
                          box-shadow: {{ states('input_select.box_shadow') }};
                        }                        
                      entities: 
                        - entity: input_text.weather_entity
                          type: 'custom:text-input-row'
                        - entity: input_text.city
                          type: 'custom:text-input-row'
                    - type: conditional
                      conditions:
                        - entity: input_boolean.system_help
                          state: "on"
                      card:
                        type: markdown                          
                        style: |
                          ha-card {
                            background: rgba(0, 0, 0, 0.5);
                            border-radius: {{ states('input_select.border_radius') }};
                            box-shadow: {{ states('input_select.box_shadow') }};
                            font-size: 13px;
                            font-family: Helvetica;
                            color: white;
                          }                        
                        content: >
                          **Air Visual:** You can set up Air Visual here, if you have set it up you can turn the addon 'on' with edit mode in the weather view.
                    - type: entities
                      title: Air Visual
                      show_header_toggle: false                          
                      style: |
                        ha-card {
                          border-radius: {{ states('input_select.border_radius') }};
                          box-shadow: {{ states('input_select.box_shadow') }};
                        }                        
                      entities: 
                        - entity: input_text.weather_entity
                          type: 'custom:text-input-row'
                        - entity: input_text.city
                          type: 'custom:text-input-row'
                        - entity: input_text.air_pollution_level
                          type: 'custom:text-input-row'
                        - entity: input_text.air_quality_index
                          type: 'custom:text-input-row'
                        - entity: input_text.main_pollutant
                          type: 'custom:text-input-row'
                    - type: markdown                          
                      style: |
                        ha-card {
                          background: rgba(0, 0, 0, 0.5);
                          border-radius: {{ states('input_select.border_radius') }};
                          box-shadow: {{ states('input_select.box_shadow') }};
                          font-size: 13px;
                          font-family: Helvetica;
                          color: white;
                        }                        
                      content: >
                        **iFrame:** The weather view has two iframe addons, if you wish to setup an iframe enter the address here and turn it on with edit mode in the weather view.
                    - type: entities
                      title: iFrames
                      show_header_toggle: false                          
                      style: |
                        ha-card {
                          border-radius: {{ states('input_select.border_radius') }};
                          box-shadow: {{ states('input_select.box_shadow') }};
                        }                        
                      entities: 
                        - entity: input_text.weather_iframe_1
                          type: 'custom:text-input-row'
                        - entity: input_text.weather_iframe_2
                          type: 'custom:text-input-row'