sensor:
  - platform: template
    sensors:
      current_lights_on:
        friendly_name: All Lights Currently On
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_light_entities','entity_id'))|selectattr('state','eq','on')|list|count }}
      current_devices_on:
        friendly_name: All Devices Currently On
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_device_switch_entities','entity_id'))|selectattr('state','eq','on')|list|count }}
      current_motion_sensors_on:
        friendly_name: All Motion Sensors Currently On
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_motion_sensor_entities','entity_id'))|selectattr('state','eq','on')|list|count }}
      current_binary_sensors_on:
        friendly_name: All Binary Sensors Currently On
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_binary_sensor_entities','entity_id'))|selectattr('state','eq','on')|list|count }}
      current_doors_open:
        friendly_name: All Doors Currently Open
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_door_sensor_entities','entity_id'))|selectattr('state','eq','on')|list|count }}
      current_windows_open:
        friendly_name: All Windows Currently Open
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_window_sensor_entities','entity_id'))|selectattr('state','eq','on')|list|count }}
      current_climate_entities_on:
        friendly_name: All Climate Entities Currently On
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_climate_entities','entity_id'))|selectattr('state','eq','heat')|list|count }}
      current_covers_open:
        friendly_name: All Covers Currently Open
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_cover_entities','entity_id'))|selectattr('state','eq','open')|list|count }}   
      current_garage_doors_open:
        friendly_name: All Garage Doors Currently Open
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_garage_door_entities','entity_id'))|selectattr('state','eq','open')|list|count }}  
      current_fans_on:
        friendly_name: All Fans Currently On
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_fan_entities','entity_id'))|selectattr('state','eq','on')|list|count }}  
      current_detectors_on:
        friendly_name: All Detectors Currently On
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_detector_entities','entity_id'))|selectattr('state','eq','on')|list|count }}  
          
  - platform: template
    sensors:
      greeting:
        friendly_name: Greeting
        value_template: >-
          {% set time = states('sensor.time') %}
          {% if '00:00' < time < '06:00' %}
            {{ states.input_text.good_night.state }}
          {% elif '06:00' < time < '12:00' %}
            {{ states.input_text.good_morning.state }}
          {% elif '12:00' < time < '18:00' %}
            {{ states.input_text.good_afternoon.state }}
          {% else %}
            {{ states.input_text.good_evening.state }}
          {% endif %}

  - platform: template
    sensors:
      hki_current_version:
        value_template: 3.1.1

  - platform: scrape
    name: HKI Latest Version
    resource: https://jimz011.github.io/homekit-infused/version
    select: ".current-version h1"
    value_template: '{{ value.split(":")[1] }}'