automation:
  # State Change Automations used for device counting
  - alias: 'group state change 1'
    id: 'State changed 1'
    trigger:
      platform: event
      event_type: state_changed
    condition: 
      condition: or
      conditions:
        - condition: template
          value_template: >
            {{ trigger.event.data.entity_id in state_attr('group.all_lighting','entity_id') }}
    action:
      service: homeassistant.update_entity
      entity_id: 
        - sensor.current_lights_on
  - alias: 'group state change 2'
    id: 'State changed 2'
    trigger:
      platform: event
      event_type: state_changed
    condition: 
      condition: or
      conditions:
        - condition: template
          value_template: >
            {{ trigger.event.data.entity_id in state_attr('group.all_device_switches','entity_id') }}
    action:
      service: homeassistant.update_entity
      entity_id: 
        - sensor.current_devices_on
  - alias: 'group state change 3'
    id: 'State changed 3'
    trigger:
      platform: event
      event_type: state_changed
    condition: 
      condition: or
      conditions:
        - condition: template
          value_template: >
            {{ trigger.event.data.entity_id in state_attr('group.all_climate_entities','entity_id') }}
    action:
      service: homeassistant.update_entity
      entity_id: 
        - sensor.current_climate_entities_on
  - alias: 'group state change 4'
    id: 'State changed 4'
    trigger:
      platform: event
      event_type: state_changed
    condition: 
      condition: or
      conditions:
        - condition: template
          value_template: >
            {{ trigger.event.data.entity_id in state_attr('group.all_computers','entity_id') }}
    action:
      service: homeassistant.update_entity
      entity_id: 
        - sensor.current_computers_on
  - alias: 'group state change 5'
    id: 'State changed 5'
    trigger:
      platform: event
      event_type: state_changed
    condition: 
      condition: or
      conditions:
        - condition: template
          value_template: >
            {{ trigger.event.data.entity_id in state_attr('group.all_tvs','entity_id') }}
    action:
      service: homeassistant.update_entity
      entity_id: 
        - sensor.current_tvs_on
  - alias: 'group state change 6'
    id: 'State changed 6'
    trigger:
      platform: event
      event_type: state_changed
    condition: 
      condition: or
      conditions:
        - condition: template
          value_template: >
            {{ trigger.event.data.entity_id in state_attr('group.all_binary_sensors','entity_id') }}
    action:
      service: homeassistant.update_entity
      entity_id: 
        - sensor.current_binary_sensors_on
  - alias: 'group state change 7'
    id: 'State changed 7'
    trigger:
      platform: event
      event_type: state_changed
    condition: 
      condition: or
      conditions:
        - condition: template
          value_template: >
            {{ trigger.event.data.entity_id in state_attr('group.all_laundry_devices','entity_id') }}
    action:
      service: homeassistant.update_entity
      entity_id: 
        - sensor.current_sensors_on
        - sensor.current_binary_sensors_on
  - alias: 'group state change 8'
    id: 'State changed 8'
    trigger:
      platform: event
      event_type: state_changed
    condition: 
      condition: or
      conditions:
        - condition: template
          value_template: >
            {{ trigger.event.data.entity_id in state_attr('group.all_door_sensors','entity_id') }}
        - condition: template
          value_template: >
            {{ trigger.event.data.entity_id in state_attr('group.all_window_sensors','entity_id') }}
    action:
      service: homeassistant.update_entity
      entity_id: 
        - sensor.current_doors_open
        - sensor.current_windows_open

  - alias: 'group state change 9'
    id: 'State changed 9'
    trigger:
      platform: event
      event_type: state_changed
    condition: 
      condition: or
      conditions:
        - condition: template
          value_template: >
            {{ trigger.event.data.entity_id in state_attr('group.all_covers','entity_id') }}
        - condition: template
          value_template: >
            {{ trigger.event.data.entity_id in state_attr('group.all_garage_doors','entity_id') }}
    action:
      service: homeassistant.update_entity
      entity_id: 
        - sensor.current_covers_open
        - sensor.current_garage_doors_open

  - alias: 'group state change 10'
    id: 'State changed 10'
    trigger:
      platform: event
      event_type: state_changed
    condition: 
      condition: or
      conditions:
        - condition: template
          value_template: >
            {{ trigger.event.data.entity_id in state_attr('group.alle_scenes','entity_id') }}
    action:
      service: homeassistant.update_entity
      entity_id: 
        - sensor.current_scenes_on

  # Theme Selector
  - alias: 'themes'
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id: input_boolean.day_night_cycle
      - platform: state
        entity_id: input_select.theme_selector
      - platform: state
        entity_id: input_select.theme_selector_day
      - platform: state
        entity_id: input_select.theme_selector_night
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: sun.sun
    action:
      - service: frontend.set_theme
        data_template:
          name: >
            {% if (is_state('sun.sun', 'above_horizon')) and (is_state('input_boolean.day_night_cycle', 'on'))  %}
              {{ states('input_select.theme_selector_day') }}
            {% elif (is_state('sun.sun', 'below_horizon')) and (is_state('input_boolean.day_night_cycle', 'on'))  %}
              {{ states('input_select.theme_selector_night') }}
            {% else %}
              {{ states('input_select.theme_selector') }}
            {% endif %}