sensor:
  - platform: template
    sensors:
      current_lights_on:
        friendly_name: All Lights Currently On
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_lighting','entity_id'))|selectattr('state','eq','on')|list|count }}
      current_devices_on:
        friendly_name: All Devices Currently On
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_device_switches','entity_id'))|selectattr('state','eq','on')|list|count }}
      current_sensors_on:
        friendly_name: All Sensors Currently On
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_motion_smoke_sensors','entity_id'))|selectattr('state','eq','on')|list|count }}
      current_binary_sensors_on:
        friendly_name: All Binary Sensors Currently On
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_binary_sensors','entity_id'))|selectattr('state','eq','on')|list|count }}
      current_doors_open:
        friendly_name: All Doors Currently Open
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_door_sensors','entity_id'))|selectattr('state','eq','on')|list|count }}
      current_windows_open:
        friendly_name: All Windows Currently Open
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_window_sensors','entity_id'))|selectattr('state','eq','on')|list|count }}
      current_climate_entities_on:
        friendly_name: All Climate Entities Currently On
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_climate_entities','entity_id'))|selectattr('state','eq','heat')|list|count }}
      current_computers_on:
        friendly_name: All Computers Currently On
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_computers','entity_id'))|selectattr('state','eq','on')|list|count }}
      current_tvs_on:
        friendly_name: All TV's Currently On
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_tvs','entity_id'))|selectattr('state','eq','on')|list|count }}
      current_laundry_devices_on:
        friendly_name: All Laundry Devices Currently On
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_laundry_devices','entity_id'))|selectattr('state','eq','on')|list|count }}   
      current_covers_open:
        friendly_name: All Covers Currently Open
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_covers','entity_id'))|selectattr('state','eq','on')|list|count }}   
      current_garage_doors_open:
        friendly_name: All Garage Doors Currently Open
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_garage_doors','entity_id'))|selectattr('state','eq','on')|list|count }}   
      current_scenes_on:
        friendly_name: All Scenes Currently On
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.alle_scenes','entity_id'))|selectattr('state','eq','on')|list|count }}   
          
  - platform: template
    sensors:
      greeting:
        friendly_name: Greeting
        value_template: >-
          {% set time = states('sensor.time') %}
          {% if '00:00' < time < '06:00' %}
            {{ states.input_text.good_night.state }}
          {% elif '06:00' < time < '12:00' %}
            {{ states.input_text.good_morning.state }}
          {% elif '12:00' < time < '18:00' %}
            {{ states.input_text.good_afternoon.state }}
          {% else %}
            {{ states.input_text.good_evening.state }}
          {% endif %}

  - platform: template
    sensors:
      hki_current_version:
        value_template: 3.0.3

  - platform: scrape
    name: HKI Latest Version
    resource: https://jimz011.github.io/homekit-infused/version
    select: ".current-version h1"
    value_template: '{{ value.split(":")[1] }}'