Home Assistant:
  ### Theme Home Assistant Default for Homekit Infused v1.2 or newer
  
  ## Lovelace Theme
  
  # Lovelace Header Text
  header-color: 'White'
  category-text: 'Black'
  paper-toast-background-color: '#821414'

  # Border Radius and Box Shadow
  border-radius: 12px
  box-shadow: var(--ha-card-box-shadow, 0px 2px 1px -1px rgba(0, 0, 0, 0.2), 0px 1px 1px 0px rgba(0, 0, 0, 0.14), 0px 1px 3px 0px rgba(0, 0, 0, 0.12) )
  bar-card-border-radius: 12px

  # Notification Badge
  notification-badge-color: 'black'
  notification-popup-action-color: 'white'

  # Primary Color
  primary-color: '#03a9f4'
  ha-card-background: 'white'
  paper-card-background-color: 'var(--ha-card-background)'