Home Assistant:
  ### Theme Home Assistant Default for Homekit Infused

  ## User Settings

  ### Background image (can be an image or a color)
  background-image: '#FFFFFF' 

  ### Header Title and Subtitle/Notifications
  header-text-color: 'White'
  header-font-size: 15px
  header-font-weight: normal

  subtitle-text-color: 'White'
  subtitle-font-size: 12px
  subtitle-font-weight: normal

  ### Title Text Addon
  title-text-color: 'Black'
  title-text-font-size: 12px
  title-text-font-weight: bolder

  ### Border Radius and Box Shadow
  border-radius: 12px
  box-shadow: var(--ha-card-box-shadow, 0px 2px 1px -1px rgba(0, 0, 0, 0.2), 0px 1px 1px 0px rgba(0, 0, 0, 0.14), 0px 1px 3px 0px rgba(0, 0, 0, 0.12) )
  bar-card-border-radius: 12px

  ### Fonts
  font-family: Roboto

  name-font-size: 12px
  name-font-weight: bold

  label-font-size: 10px
  label-font-weight: normal

  state-font-size: 10px
  state-font-weight: bold

  ### Badges
  badge-font-size: 10px
  badge-font-weight: normal
  badge-text-transform: capitalize
  

  #######################################################################################################################################################
  ## Main Home Assistant Colors (ANYTHING YOU CHANGE PAST THIS LINE, IS AT YOUR OWN RISK!)

  # Primary Color
  primary-color: '#03a9f4'
  ha-card-background: 'white'
  paper-card-background-color: 'var(--ha-card-background)'
  paper-toast-background-color: '#821414'