# DOORS OPEN WILL SEND ALERTS TO IOS APP (v2.0 required)
- alias: Voordeur
  initial_state: 'true'
  trigger:
  - platform: state
    entity_id: binary_sensor.voordeur
    to: 'on'
  - platform: state
    entity_id: binary_sensor.voordeur
    to: 'off'
  action:
  - service_template: >
        {% if (is_state('person.jimmy', 'not_home')) and (is_state('person.stephanie', 'not_home'))  %}
          notify.ios_notifier
        {% elif (is_state('person.jimmy', 'home')) and (is_state('person.stephanie', 'not_home')) %}
          notify.ios_notifier
        {% elif (is_state('person.jimmy', 'not_home')) and (is_state('person.stephanie', 'home')) %}
          notify.mobile_app_iphone
        {% elif (is_state('person.jimmy', 'home')) and (is_state('person.stephanie', 'home')) %}
          notify.mobile_app_iphone
        {% endif %}
    data_template:
      title: "Voordeur"
      message: >
        {% if is_state('binary_sensor.voordeur', 'on') %}
          De Voordeur is zojuist geopend!
        {% elif is_state('binary_sensor.voordeur', 'off') %}
          De Voordeur is zojuist gesloten!
        {% endif %}
      data:
        push:
          sound: default

- alias: Woonkamer Deur
  initial_state: 'true'
  trigger:
  - platform: state
    entity_id: binary_sensor.woonkamer_deur
    to: 'on'
  - platform: state
    entity_id: binary_sensor.woonkamer_deur
    to: 'off'
  action:
  - service_template: >
        {% if (is_state('person.jimmy', 'not_home')) and (is_state('person.stephanie', 'not_home'))  %}
          notify.ios_notifier
        {% elif (is_state('person.jimmy', 'home')) and (is_state('person.stephanie', 'not_home')) %}
          notify.mobile_app_iphone_stephanie
        {% elif (is_state('person.jimmy', 'not_home')) and (is_state('person.stephanie', 'home')) %}
          notify.mobile_app_iphone
        {% endif %}
    data_template:
      title: "Woonkamer Deur"
      message: >
        {% if is_state('binary_sensor.woonkamer_deur', 'on') %}
          De Woonkamer Deur is zojuist geopend!
        {% elif is_state('binary_sensor.woonkamer_deur', 'off') %}
          De Woonkamer Deur is zojuist gesloten!
        {% endif %}
      data:
        push:
          sound: default

- alias: Slaapkamer Deur
  initial_state: 'true'
  trigger:
  - platform: state
    entity_id: binary_sensor.slaapkamer_deur
    to: 'on'
  - platform: state
    entity_id: binary_sensor.slaapkamer_deur
    to: 'off'
  action:
  - service_template: >
        {% if (is_state('person.jimmy', 'not_home')) and (is_state('person.stephanie', 'not_home'))  %}
          notify.ios_notifier
        {% elif (is_state('person.jimmy', 'home')) and (is_state('person.stephanie', 'not_home')) %}
          notify.mobile_app_iphone_stephanie
        {% elif (is_state('person.jimmy', 'not_home')) and (is_state('person.stephanie', 'home')) %}
          notify.mobile_app_iphone
        {% endif %}
    data_template:
      title: "Slaapkamer Deur"
      message: >
        {% if is_state('binary_sensor.slaapkamer_deur', 'on') %}
          De Slaapkamer Deur is zojuist geopend!
        {% elif is_state('binary_sensor.slaapkamer_deur', 'off') %}
          De Slaapkamer Deur is zojuist gesloten!
        {% endif %}
      data:
        push:
          sound: default
    