theme: jekyll-theme-slate
show_downloads: false
title: Homekit Infused
google_analytics: UA-158593402-1
buttons:
  zip_url: https://github.com/jimz011/homekit-infused/archive/refs/tags/4.0.0e.zip
  zip_title: Download latest release
  zip_hide: false
  tar_hide: true
